name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make build
      - name: Lint with flake8
        run: make static_checks
      - name: Test with pytest
        run: make test
      - name: Get coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: output/coverage.xml
          token: ${{ secrets.GH_TOKEN }}
